version: '3'

services:
  mariadb:
    image: bitnami/mariadb:10.6
    container_name: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=bitnami_magento
    ports:
      - "3306:3306"
    volumes:
      - ./db_init:/docker-entrypoint-startdb.d
    networks:
      - magento-network
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "bn_magento", "-pbitnami", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  elasticsearch:
    image: elasticsearch:7.17.18
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - magento-network
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      retries: 5

  magento:
    image: bitnami/magento:2.4.6 # 2.4.6-p4
    container_name: magento
    depends_on:
      elasticsearch:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    ports:
      - "80:8080"
      - "443:8443"
      - "9003:9003"
    environment:
      - MAGENTO_HOST=localhost
      - BITNAMI_DEBUG = "true"
      - ALLOW_EMPTY_PASSWORD=yes
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=bitnami
      - MAGENTO_DATABASE_NAME=bitnami_magento
    networks:
      - magento-network

networks:
  magento-network:

